main/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('genre/<str:slug>/', category_detail, name='category'),
    path('film_detail/<int:pk>/', film_detail, name='detail'),
    path('add_new_film/', create, name='create'),
    path('update/<int:pk>/', update, name='update'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('search/', SearchListView.as_view(), name='search'),
    path('film_detail/<int:pk>/comment', leave_comment, name='leave_comment'),
    path('news/', main, name='parse_news'),
    path('watch/<int:pk>/', watch, name='watch')
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('main.cart_urls')),
    path('accounts/', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models


class Genre(models.Model):
    slug = models.SlugField(primary_key=True, max_length=150)
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='genres', default='account/default.jpg', blank=True, null=True)

    def __str__(self):
        return self.name


class Films(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    year = models.CharField(max_length=10)
    country = models.CharField(max_length=100)
    time = models.CharField(max_length=150)
    producer = models.CharField(max_length=100)
    genre = models.ManyToManyField(Genre)
    image = models.ImageField(upload_to='films')
    video = models.FileField(upload_to='video')

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    film = models.ForeignKey(Films, on_delete=models.CASCADE)
    author = models.CharField('Author: ', max_length=50)
    comment_text = models.CharField('Comment: ', max_length=500)

    def __str__(self):
        return self.author

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cinematica</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="./index.html">
                            <img src="img/logo.png" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="{% url 'home' %}">Homepage</a></li>
                                <li><a href="#">Categories <span class="arrow_carrot-down"></span></a>
                                    <ul class="dropdown">
                                        {% for genre in categories %}
                                        <li><a href="{% url 'category' genre.slug %}">{{genre}}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                <li><a href="{% url 'parse_news' %}">News</a></li>
                                {% if request.user.is_authenticated %}
                                <li><a href="{% url 'logout' %}">Log out</a></li>
                                                                <li><a href="{% url 'favorities' %}">Favorities</a></li>
                                {% endif %}
                                 {% if request.user.is_staff and request.user.is_superuser %}
                                <li><a href="{% url 'create' %}">Create</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <form class="d-flex" method="get" action="{% url 'search' %}">
      <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
                        {% if not request.user.is_authenticated %}
                        <a href="{% url 'login' %}"><span class="icon_profile"></span></a>
                        {% else %}
                        <a href="{% url 'profile' %}"><span class="icon_profile"></span></a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>


    </header>
{% block content %} {% endblock %}
<!-- Footer Section Begin -->
<footer class="footer">
    <div class="page-up">
        <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="footer__logo">
                    <a href="./index.html"><img src="img/logo.png" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="footer__nav">
                    <ul>
                        <li class="active"><a href="{% url 'home' %}">Homepage</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3">
                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                  Copyright &copy;<script>document.write(new Date().getFullYear());</script>blablablablalbalbnalbajnvsjowb,mwfobofqouc<i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>

              </div>
          </div>
      </div>
  </footer>
  <!-- Footer Section End -->

  <!-- Search model Begin -->
  <div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch"><i class="icon_close"></i></div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search model end -->

<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/player.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


</body>

</html>

templates/cart_detail.html
{% extends 'base.html' %}
{% block content %}
{% load cart_tag %}
 <div class="row">
          {% for key, film in request.session.cart.items %}
          <div class="col-lg-4 col-md-6 col-sm-6">
              <div class="product__item">
                  <div class="product__item__pic set-bg" data-setbg="{{ film.image }}"></div>
                  <div class="product__item__text">
                      <h5><a href="{% url 'detail' film.product_id %}">{{ film.name }}</a></h5>
                  </div>
                      <div class="anime__details__btn"> <a href="{% url 'item_clear' film.product_id %}" class="watch-btn"><span>Clear</span> </a>
                      </div>
                      </div>
          </div>
          {% endfor %}
      </div>
    <div class="anime__details__btn"> <a href="{% url 'cart_clear' %}" class="watch-btn"><span>Cart Clear</span> </a>
    </div>
{% endblock %}

templates/categories.html
{% extends 'base.html' %}
{% block content %}

<section class="product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="trending__product">
                        <div class="row">
                            <div class="col-lg-8 col-md-8 col-sm-8">
                                <div class="section-title">
                                    <h4>{{categori}}</h4>
                                </div>
                            </div>
<!--                            <div class="col-lg-4 col-md-4 col-sm-4">-->
<!--                                <div class="btn__all">-->
<!--                                    <a href="#" class="primary-btn">View All <span class="arrow_right"></span></a>-->
<!--                                </div>-->
<!--                            </div>-->
                        </div>
                        <div class="row">
                            {% for film in page_obj %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product__item">
                                    <div class="product__item__pic set-bg" data-setbg="{{ film.image.url }}">
                                    </div>
                                    <div class="product__item__text">
                                        <h5><a href="{% url 'detail' film.pk %}">{{ film.title}}</a></h5>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>

<div class="product__pagination">
    {% for p in page_obj.paginator.page_range %}
        <a href="?page={{p}}" class="current-page">{{p}}</a>

{% endfor %}
     </div>
{% endblock %}

templates/create.html
{% extends 'base.html' %}
{% block content %}
<form style="color: #fff;" method="post" enctype="multipart/form-data">
    {{ film_form.as_p}}
        {% csrf_token %}
<button type="submit" class="btn btn-secondary">Add</button>
</form>

{% endblock %}

templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form style="color: #fff;" method="post" enctype="multipart/form-data">
    <h1>Are you sure?</h1>
        {% csrf_token %}
<button type="submit" class="btn btn-danger">Yes</button>

</form>
    <a href="{% url 'detail' film.pk %}"> <button class="btn btn-warning">No</button></a>
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% block content %}

    <section class="anime-details spad">
        <div class="container">
            <div class="anime__details__content">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="anime__details__pic set-bg" data-setbg="{{ film.image.url }}">
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="anime__details__text">
                            <div class="anime__details__title">
                                <h3>{{film.title}}</h3>
                            <p>{{film.description}}</p>
                            <div class="anime__details__widget">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <ul>
                                            <li><span>Date aired:</span> {{film.year}}</li>
                                            <li><span>Time:</span> {{film.time}} min</li>
                                            <li><span>Quality:</span> HD</li>
                                          <li><span>Producer:</span> {{film.producer}}</li>
                                             <li><span>Country:</span> {{film.country}}</li>
                                        </ul>
                                </div>
                            </div>
                            <div class="anime__details__btn">
                                <a href="{% url 'cart_add' film.pk %}" class="follow-btn"><i class="fa fa-heart-o"></i> Follow</a>
                                <a href="{% url 'watch' film.pk %}" class="watch-btn"><span>Watch Now</span> <i
                                    class="fa fa-angle-right"></i></a>
                                </div>
                                {% if request.user.is_staff and request.user.is_superuser and request.user.is_authenticated %}
                                <a href="{% url 'update' film.pk %}"><img src="https://img.icons8.com/material-sharp/30/000000/edit--v1.png"/></a>
                                <a href="{% url 'delete' film.pk %}"><img src="https://img.icons8.com/material/30/000000/filled-trash.png"/></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>

                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <div class="anime__details__review">
                            <div class="section-title">
                                <h5>Reviews</h5>
                            </div>

{% if comment_list %}
			{% for comment in comment_list %}

                            <div class="anime__review__item">
                                <div class="anime__review__item__pic">
                                    <img src="{{ request.user.image.url }}" alt="">
                                </div>
                                <div class="anime__review__item__text">
                                    <h6>{{comment.author}} <span>{{comment.datetime}}</span></h6>
                                    <p>{{comment.comment_text}}</p>
                                </div>
                            </div>

{% endfor %}
{% else %}
<p style="margin-top: center;">Комментарий нет! Будьте первым!</p>
{% endif %}


                        <div class="anime__details__form">
                            <div class="section-title">
                                <h5>Your Comment</h5>
                            </div>
                            <form method="post" action="{% url 'leave_comment' film.pk %}">
                                {% csrf_token %}
                                <textarea name="comment" placeholder="Send Comment"></textarea>
                                		<li><input type="submit" value="Send" class="primary" /></li>

                            </form>
                        </div>
                    </div>
                    </div>
            </div>
        </section>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Hero Section Begin -->
    <section class="hero">
        <div class="container">
            <div class="hero__slider owl-carousel">
                <div class="hero__items set-bg" data-setbg="{% static 'imgg/c5.jpg' %}">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="hero__text">
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>

                                <br>
                                <br>
                                <a href="#"><span>Creators: Winx</span> </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="hero__items set-bg" data-setbg="{% static 'imgg/c4.jpg' %}">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="hero__text">

                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>

                                <a href="#"><span>Creators: Winx</span> </a>

<!--                                <a href="#"><span>Watch Now</span> <i class="fa fa-angle-right"></i></a>-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="hero__items set-bg" data-setbg="{% static 'imgg/c8.jpg' %}">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="hero__text">
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>

                                <a href="#"><span>Creators: Winx</span> </a>

<!--                                <a href="#"><span>Watch Now</span> <i class="fa fa-angle-right"></i></a>-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="hero__items set-bg" data-setbg="{% static 'imgg/c2.jpg' %}">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="hero__text">
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>

                                <a href="#"><span>Creators: Winx</span> </a>

<!--                                <a href="#"><span>Watch Now</span> <i class="fa fa-angle-right"></i></a>-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="hero__items set-bg" data-setbg="{% static 'imgg/c1.jpg' %}">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="hero__text">
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>

                                <br>
                                <br>
                                <br>
                                <a href="#"><span>Creators: Winx</span> </a>

<!--                                <a href="#"><span>Watch Now</span> <i class="fa fa-angle-right"></i></a>-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="hero__items set-bg" data-setbg="{% static 'imgg/c7.jpg' %}">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="hero__text">
                                <br>
                                <br>
                                <br>

                                <br>
                                <br>
                                                                <a href="#"><span>Creators: Winx</span> </a>

<!--                                <a href="#"><span>Watch Now</span> <i class="fa fa-angle-right"></i></a>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Product Section Begin -->
    <section class="product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="trending__product">
                        <div class="row">
                            <div class="col-lg-8 col-md-8 col-sm-8">
                                <div class="section-title">
                                    <h4>Recently</h4>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            {% for film in films %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product__item">
                                    <div class="product__item__pic set-bg" data-setbg="{{ film.image.url }}">
                                        <div class="ep">18 / 18</div>
                                    </div>
                                    <div class="product__item__text">
                                        <h5><a href="{% url 'detail' film.pk %}">{{ film.title}}</a></h5>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>

{% endblock %}

templates/news.html
{% extends 'base.html' %}
{% block content %}
    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <div class="blog__details__title">
                        <h2>Последние новости из индустрии кино</h2>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="img/blog/details/blog-details-pic.jpg" alt="">
                    </div>
                </div>
                <div class="col-lg-8">

                    <div class="blog__details__content">
                        {% for new in news %}
                        <div class="blog__details__item__text">
                            <h4>{{ new.title }}</h4>
                            <p>{{ new.description }}</p>
                            <a target="_blank" href="{{ new.link }}"><button type="submit" class="site-btn">Read</button></a>
                            </div>
                        {% endfor %}


                            <div class="blog__details__comment">
                                <h4>3 Comments</h4>
                                <div class="blog__details__comment__item">
                                    <div class="blog__details__comment__item__pic">
                                        <img src="img/blog/details/comment-1.png" alt="">
                                    </div>
                                    <div class="blog__details__comment__item__text">
                                        <span>Sep 08, 2020</span>
                                        <h5>John Smith</h5>
                                        <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
                                        adipisci velit, sed quia non numquam eius modi</p>
                                        <a href="#">Like</a>
                                        <a href="#">Reply</a>
                                    </div>
                                </div>
                                <div class="blog__details__comment__item blog__details__comment__item--reply">
                                    <div class="blog__details__comment__item__pic">
                                        <img src="img/blog/details/comment-2.png" alt="">
                                    </div>
                                    <div class="blog__details__comment__item__text">
                                        <span>Sep 08, 2020</span>
                                        <h5>Elizabeth Perry</h5>
                                        <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
                                        adipisci velit, sed quia non numquam eius modi</p>
                                        <a href="#">Like</a>
                                        <a href="#">Reply</a>
                                    </div>
                                </div>
                                <div class="blog__details__comment__item">
                                    <div class="blog__details__comment__item__pic">
                                        <img src="img/blog/details/comment-3.png" alt="">
                                    </div>
                                    <div class="blog__details__comment__item__text">
                                        <span>Sep 08, 2020</span>
                                        <h5>Adrian Coleman</h5>
                                        <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
                                        adipisci velit, sed quia non numquam eius modi</p>
                                        <a href="#">Like</a>
                                        <a href="#">Reply</a>
                                    </div>
                                </div>
                            </div>
                            <div class="blog__details__form">
                                <h4>Leave A Commnet</h4>
                                <form action="#">
                                    <div class="row">
                                        <div class="col-lg-6 col-md-6 col-sm-6">
                                            <input type="text" placeholder="Name">
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-6">
                                            <input type="text" placeholder="Email">
                                        </div>
                                        <div class="col-lg-12">
                                            <textarea placeholder="Message"></textarea>
                                            <button type="submit" class="site-btn">Send Message</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Blog Details Section End -->
{% endblock %}

templates/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form style="color: black;" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ film_form.as_p }}
<button type="submit" class="btn btn-secondary">Add</button>
</form>

{% if img_obj %}
  <h3>Succesfully uploaded : {{img_obj.title}}</h3>
  <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
{% endif %}


{% endblock %}

templates/watch.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <section class="anime-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="anime__video__player">
                        <video id="player" playsinline controls data-poster="./videos/anime-watch.jpg">
                            <source src="{{ film.video.url }}" type="video/mp4" />
                            <track kind="captions" label="English captions" src="#" srclang="en" default />
                        </video>
                    </div>
                </div>
            </div>
 <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <div class="anime__details__review">
                            <div class="section-title">
                                <h5>Reviews</h5>
                            </div>

{% if comment_list %}
			{% for comment in comment_list %}

                            <div class="anime__review__item">
                                <div class="anime__review__item__pic">
                                    <img src="{% static 'imgg/default.jpg' %}" alt="">
                                </div>
                                <div class="anime__review__item__text">
                                    <h6>{{comment.author}} <span>{{comment.datetime}}</span></h6>
                                    <p>{{comment.comment_text}}</p>
                                </div>
                            </div>

{% endfor %}
{% else %}
<p style="margin-top: center;">Комментарий нет! Будьте первым!</p>
{% endif %}


                        <div class="anime__details__form">
                            <div class="section-title">
                                <h5>Your Comment</h5>
                            </div>
                            <form method="post" action="{% url 'leave_comment' film.pk %}">
                                {% csrf_token %}
                                <textarea placeholder="Your Comment"></textarea>
                                		<li><input type="submit" value="Send" class="primary" /></li>

                            </form>
                        </div>
                    </div>
                    </div>
            </div>
            </div>
        </div>
    </section>
{% endblock %}